gene:
  num_epochs: 100
  conv_type: 'mndgcn'
  hidden_dim: 256
  num_layers: 3
  jk: 'cat'
  alpha: 0.5
  dropout: 0.5
  beta: 0.0003
  lr: 0.01
  patience: 5
  num_runs: 1
  normalize: True
  weight_decay: 0.0